language: c
compiler:
  - gcc
before_install:
    - sudo apt-get update
    - sudo apt-get install gradle
script: LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)/build" make test && make clean && make bindings
